### PR TITLE
fix: collect tests of subprojects in multi-project setups

### LINKED ISSUE #54: Multiproject builds do not pick up tests of subprojects
### Description

Plugin does not pick up tests of subprojects (used Gradle 5.6.2)

### How to reproduce

1. Create Gradle Multiproject
2. Add `gradle-metrics-plugin` to root project
3. Add java subproject containing tests
4. Run `test` task

#### Result

No tests are displayed in the report

### Fix

Perform scan for tasks of the type `Test` after evaluation of the subproject

### PR DESCRIPTION
**Pull request by error418**
fixes #54

### CODE REVIEW

**Comment by rpalcolea** [comment]
Hi @error418 , thanks for your contribution.

Any chance you could add a test to verify the new expected behavior?

**Comment by error418** [comment]
Sure - I will look into it

**Comment by error418** [comment]
Added a test covering the issue

**Comment by rpalcolea** [comment]
awesome! thanks for the contribution

**Comment by rpalcolea** [comment]
This is now available on 9.0.1

**Pull request merged**
